# Generated by Django 5.2.5 on 2025-08-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_two',
            field=models.CharField(default='phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='phone', max_length=20),
        ),
    ]
