# Generated by Django 5.2.5 on 2025-08-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_contact_phone_two_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area', models.FloatField(help_text='Площадь в квадратных метрах')),
                ('area_ga', models.FloatField(help_text='Площадь в гектарах/сотках')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('is_active_new', models.BooleanField(default=True)),
                ('is_active_sold', models.BooleanField(default=False)),
                ('contacts', models.ManyToManyField(related_name='properties', to='webapp.contact')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='property_photos/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='webapp.property')),
            ],
        ),
    ]
