# Generated by Django 5.2.5 on 2025-08-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.FloatField(default=0, help_text='Этаж'),
        ),
        migrations.AddField(
            model_name='property',
            name='many_rooms',
            field=models.FloatField(default=0, help_text='Сколько комнат'),
        ),
        migrations.AddField(
            model_name='property',
            name='notes',
            field=models.TextField(default='Примечание'),
        ),
    ]
