# Generated by Django 5.2.5 on 2025-08-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_property_floor_property_many_rooms_property_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.TextField(default=0, help_text='Этаж'),
        ),
        migrations.AlterField(
            model_name='property',
            name='many_rooms',
            field=models.TextField(default=0, help_text='Сколько комнат'),
        ),
    ]
