# Generated by Django 5.2.5 on 2025-08-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_property_floor_alter_property_many_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area_ga',
            field=models.FloatField(blank=True, help_text='Площадь в гектарах/сотках', null=True),
        ),
    ]
