# Generated by Django 5.2.5 on 2025-08-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_property_area_ga'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_active_apartment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_active_house',
            field=models.BooleanField(default=True),
        ),
    ]
