# Generated by Django 5.2.5 on 2025-08-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_property_is_active_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_rent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_sale',
            field=models.BooleanField(default=True),
        ),
    ]
