# Generated by Django 5.2.5 on 2025-08-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_property_is_rent_property_is_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('BYN', 'BYN')], default='USD', max_length=3),
        ),
    ]
