# Generated by Django 5.2.5 on 2025-08-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_property_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_active_country_house',
            field=models.BooleanField(default=True),
        ),
    ]
