# Generated by Django 5.2.5 on 2025-08-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_property_is_active_country_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('property_address', models.CharField(max_length=255, verbose_name='Адрес объекта')),
                ('video_url', models.URLField(max_length=500, verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Видео объекта',
                'verbose_name_plural': 'Видео объектов',
                'ordering': ['-date'],
            },
        ),
    ]
