# Generated by Django 5.2.5 on 2025-08-20 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_propertyvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='MainSliderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='main_slider_photos/')),
                ('desc_text', models.CharField(blank=True, max_length=255)),
                ('name_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='webapp.mainslider')),
            ],
        ),
    ]
