# Generated by Django 5.2.5 on 2025-08-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_mainslider_mainsliderphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_objects', models.PositiveIntegerField(default=1000, verbose_name='Объектов продано')),
                ('avg_sale_days', models.PositiveIntegerField(default=21, verbose_name='Средний срок продажи (дней)')),
                ('support_247', models.CharField(default='24', max_length=10, verbose_name='На связи (часов в сутки)')),
            ],
            options={
                'verbose_name': 'Статистика доверия',
                'verbose_name_plural': 'Статистика доверия',
            },
        ),
    ]
