# Generated by Django 5.2.5 on 2025-08-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_truststats'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=100, verbose_name='Класс иконки FontAwesome')),
                ('text', models.CharField(max_length=100, verbose_name='Текст причины')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Причина доверия',
                'verbose_name_plural': 'Причины доверия',
                'ordering': ['order'],
            },
        ),
    ]
