# Generated by Django 5.2.5 on 2025-08-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_trustreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city_name',
            field=models.CharField(default='город', max_length=255),
        ),
    ]
