# Generated by Django 5.2.5 on 2025-08-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_property_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя компании')),
                ('photo', models.ImageField(upload_to='about_photos/', verbose_name='Фото компании')),
                ('description', models.TextField(verbose_name='Описание')),
                ('unp', models.CharField(blank=True, max_length=100, null=True, verbose_name='УНП')),
                ('license', models.CharField(blank=True, max_length=100, null=True, verbose_name='Лицензия')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
        ),
    ]
