# Generated by Django 5.2.5 on 2025-08-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Объекты', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'verbose_name': 'Соц сети', 'verbose_name_plural': 'Соц сети'},
        ),
        migrations.AlterField(
            model_name='property',
            name='contacts',
            field=models.ManyToManyField(related_name='properties', to='webapp.contact', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='property',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('BYN', 'BYN')], default='USD', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='property',
            name='date_posted',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active_apartment',
            field=models.BooleanField(default=True, verbose_name='Доступна квартира'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active_country_house',
            field=models.BooleanField(default=True, verbose_name='Доступен загородный дом'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active_house',
            field=models.BooleanField(default=True, verbose_name='Доступен дом'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active_new',
            field=models.BooleanField(default=True, verbose_name='Новое объявление'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active_sold',
            field=models.BooleanField(default=False, verbose_name='Продан'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_rent',
            field=models.BooleanField(default=True, verbose_name='Сдается в аренду'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_sale',
            field=models.BooleanField(default=True, verbose_name='Продается'),
        ),
    ]
