# Generated by Django 5.2.5 on 2025-08-27 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_alter_about_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainslider',
            options={'verbose_name': 'Главный слайдер', 'verbose_name_plural': 'Главные слайдеры'},
        ),
        migrations.AlterModelOptions(
            name='mainsliderphoto',
            options={'verbose_name': 'Фото слайдера', 'verbose_name_plural': 'Фото слайдера'},
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название слайдера'),
        ),
        migrations.AlterField(
            model_name='mainsliderphoto',
            name='desc_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainsliderphoto',
            name='name_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='webapp.mainslider', verbose_name='Слайдер'),
        ),
        migrations.AlterField(
            model_name='mainsliderphoto',
            name='photo',
            field=models.ImageField(upload_to='main_slider_photos/', verbose_name='Фото слайда'),
        ),
    ]
