# Generated by Django 5.2.5 on 2025-08-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_alter_mainslider_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.FloatField(help_text='Площадь в квадратных метрах', verbose_name='Полщадь м/кв'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area_ga',
            field=models.FloatField(blank=True, help_text='Площадь в гектарах/сотках', null=True, verbose_name='Площадь в гектарах/сотках'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city_name',
            field=models.CharField(default='город', max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.TextField(default=0, help_text='Этаж', verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='property',
            name='many_rooms',
            field=models.TextField(default=0, help_text='Сколько комнат', verbose_name='Сколько комнат'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя/Адрес'),
        ),
        migrations.AlterField(
            model_name='property',
            name='notes',
            field=models.TextField(default='Примечание', verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Для адресной строки ЮРЛ'),
        ),
    ]
