# Generated by Django 5.2.5 on 2025-09-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_alter_property_address_alter_property_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='is_had',
            field=models.BooleanField(default=True, verbose_name='В верхнее меню'),
        ),
    ]
