# Generated by Django 5.2.5 on 2025-09-05 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_socialnetwork_is_had'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon_svg', models.FileField(blank=True, help_text='SVG файл иконки', null=True, upload_to='messenger_svgs/')),
                ('is_had', models.BooleanField(default=True, verbose_name='В верхнее меню')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messengers', to='webapp.contact')),
            ],
            options={
                'verbose_name': 'Мессенджеры',
                'verbose_name_plural': 'Мессенджеры',
            },
        ),
    ]
