# Generated by Django 5.2.5 on 2025-09-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_messengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_commercial',
            field=models.BooleanField(default=True, verbose_name='Коммерческая'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_top_ten',
            field=models.BooleanField(default=True, verbose_name='Топ 10'),
        ),
    ]
