# Generated by Django 5.2.5 on 2025-09-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_property_is_commercial_property_is_top_ten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_active_apartment',
            field=models.BooleanField(default=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active_country_house',
            field=models.BooleanField(default=True, verbose_name='Загородный дом'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active_house',
            field=models.BooleanField(default=True, verbose_name='Дом'),
        ),
    ]
