# Generated by Django 5.2.5 on 2025-09-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_alter_property_is_active_apartment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО сотрудника')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Количество отзывов')),
                ('agency_name', models.CharField(max_length=255, verbose_name='Название агентства')),
                ('agency_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL агентства')),
                ('regions', models.TextField(blank=True, verbose_name='Регионы работы')),
                ('specialties', models.TextField(blank=True, verbose_name='Специализация')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='Фото сотрудника')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
    ]
