# Generated by Django 5.2.5 on 2025-09-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='map_embed_html',
            field=models.TextField(blank=True, null=True, verbose_name='HTML-код карты (iframe)'),
        ),
    ]
