# Generated by Django 5.2.5 on 2025-10-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_city_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_active_newstroy',
            field=models.BooleanField(default=True, verbose_name='Новостройки'),
        ),
    ]
